# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def setup_method(self, method):
    self.driver = webdriver.Edge()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    # Test name: 练习赛1
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://petclinic.k8s.hogwarts.ceshiren.com/")
    # 2 | setWindowSize | 947x692 |  | 
    self.driver.set_window_size(947, 692)
    # 3 | click | css=.dropdown-toggle |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-toggle").click()
    # 4 | click | css=li:nth-child(2) > a > span:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a > span:nth-child(2)").click()
    # 5 | click | name=firstName |  |
    time.sleep(3)
    self.driver.find_element(By.NAME, "firstName").click()
    # 6 | type | name=firstName | ceshiren | 
    self.driver.find_element(By.NAME, "firstName").send_keys("ceshiren")
    # 7 | type | name=lastName | ceshiren | 
    self.driver.find_element(By.NAME, "lastName").send_keys("ceshiren")
    # 8 | type | name=address | ceshiren | 
    self.driver.find_element(By.NAME, "address").send_keys("ceshiren")
    # 9 | type | name=city | 东莞市 | 
    self.driver.find_element(By.NAME, "city").send_keys("东莞市")
    # 10 | type | name=telephone | 15826158825 | 
    self.driver.find_element(By.NAME, "telephone").send_keys("15826158825")
    # 11 | click | css=.btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
